/*
 * Copyright (c) 2015 Varnish Software AS
 * All rights reserved.
 *
 * Author: Martin Blix Grydeland <martin@varnish-software.com>
 *
 * See man SSL_get_error(3SSL) */

SSL_ERR(SSL_ERROR_NONE)
SSL_ERR(SSL_ERROR_ZERO_RETURN)
SSL_ERR(SSL_ERROR_WANT_READ)
SSL_ERR(SSL_ERROR_WANT_WRITE)
SSL_ERR(SSL_ERROR_WANT_CONNECT)
SSL_ERR(SSL_ERROR_WANT_ACCEPT)
SSL_ERR(SSL_ERROR_WANT_X509_LOOKUP)
SSL_ERR(SSL_ERROR_SYSCALL)
SSL_ERR(SSL_ERROR_SSL)
SSL_ERR(SSL_ERROR_WANT_ASYNC)
SSL_ERR(SSL_ERROR_WANT_ASYNC_JOB)
SSL_ERR(SSL_ERROR_WANT_CLIENT_HELLO_CB)
SSL_ERR(SSL_ERROR_WANT_RETRY_VERIFY)
