name: Compile and Check

on:
  push:
    branches:
      - "*"
    tags:
      - varnish-*
  workflow_dispatch:

jobs:
  make_dist:
    name: Create distribution tarball
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            ca-certificates \
            cpio \
            git \
            libedit-dev \
            libjemalloc-dev \
            libncurses-dev \
            libpcre2-dev \
            libssl-dev \
            libtool \
            libunwind-dev \
            pkg-config \
            python3-sphinx

      - name: Build distribution tarball
        run: |
          ./autogen.sh
          ./configure
          make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v7
        with:
          name: dist-tarball
          path: varnish-*.tar.gz
          retention-days: 1

  release:
    if: startsWith(github.event.ref, 'refs/tags/')
    name: Create release
    needs: make_dist
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - &download_tarball
        name: Download tarball
        uses: actions/download-artifact@v8
        with:
          name: dist-tarball

      - name: Configure version matches tag
        run: |
          tar xzf varnish-*.tar.gz --strip 1
          CONFIGURE_VERSION=$(./configure --version | awk 'NR == 1 {print $NF}')
          echo "CONFIGURE_VERSION=$CONFIGURE_VERSION" >> "$GITHUB_ENV"
          echo "configure version: $CONFIGURE_VERSION"
          echo "tag: ${{ github.ref_name}}"
          test ${{ github.ref_name}} = "varnish-$CONFIGURE_VERSION"

      - name: Changelog section exists
        run: |
          echo "Making sure that there's a \"Varnish-Cache $CONFIGURE_VERSION (DATE)\" section in doc/changes.rst"
          grep -E "Varnish-Cache $CONFIGURE_VERSION \([0-9]{4}-[0-9]{2}-[0-9]{2}\)" doc/changes.rst

      - name: Extract release section
        run: |
          # I'm sure there's a sed one-liner for this...
          awk -v "ver=$CONFIGURE_VERSION" '
                            capture==1 && !/^====/{
                              print $0
                            }
                            $1 == "Varnish-Cache" && $2 == ver {
                              pre=1
                            }
                            /^=====/ {
                              capture=pre;
                              pre=0;
                            }' doc/changes.rst | tee release.rst

      - name: Markdownify release notes
        uses: docker://pandoc/core:3.8
        with:
          args: release.rst -f rst -t markdown -o release.md

      - name: Draft release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat release.md
          ls
          gh release create -d -t $CONFIGURE_VERSION --verify-tag ${{ github.ref_name}} -F release.md varnish-*.tar.gz
